name: "Github Tag with semantic versioning"
description: "Bump and push git tag on merge"
author: "Mathieu Dutour (hacked by Jörg Henne)"
outputs:
  new_tag:
    description: "Generated tag"
  previous_tag:
    description: "Previous tag (or `0.0.0`)"
inputs:
  github_token:
    description: "Required for permission to tag the repo."
    required: true
  default_bump:
    description: "Which type of bump to use when none explicitly provided (default: `patch`)."
    required: false
    default: "patch"
  tag_prefix:
    description: "A prefix to the tag name (default: `v`)."
    required: false
    default: "v"
  release_branches:
    description: "Comma separated list of branches (bash reg exp accepted) that will generate the release tags. Other branches and pull-requests generate versions postfixed with the commit hash and do not generate any tag. Examples: `master` or `.*` or `release.*,hotfix.*,master`..."
    required: false
    default: "master"
  create_annotated_tag:
    description: "Boolean to create an annotated tag rather than lightweight"
    required: false
    default: "false"
  dry_run:
    description: "Do not perform taging, just calculate next version and changelog, then exit"
    required: false
    default: "false"
  message_parser_preset:
    description: >
      The name of a (commit-analyzer preset)[https://github.com/semantic-release/commit-analyzer#options] to be used
      to parse the commit messages. Possible values are
      * (angular)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular]
      * (atom)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-atom]
      * (codemirror)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-codemirror]
      * (ember)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-ember]
      * (eslint)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint]
      * (express)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-express]
      * (jquery)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-jquery]
      * (jshint)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-jshint]
      * (conventionalcommits)[https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits]
    required: false
    default: conventionalcommits

runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "git-merge"
  color: "purple"
